/*
 Generated by node-express website
 @file webone
 @author TimYao <tmwoman@yeah.net>
 @version 2015071022

 Development of the underlying
 node express ejs

 */

 var express = require('express'),
     bodyParder = require('body-parser'),    //参数处理
     cookie = require('cookie-parser'),      //cookie 
     sesstion = require('express-session'),  //session
     logger = require('morgan'),   //日志
     timeout = require('timeout'), //延时用法
     multer = require('multer');   //上传
     cookie = require('cookie-parser'),
     session = require('express-session'),
     routers = require('../routers/routers.js'),
     app = express(),
     port = process.env.PORT || 1000,
     host = '127.0.0.1',
     dirname = __dirname,
     platform = process.platform,
     time = 5000,
     env = app.get('env').toLowerCase() === 'development' ? 'development' : 'production',
     systems = {
     	 "win":"win"
     };

//设置
app.set("view engine","ejs");
app.set("views",dirname+checkPlat(platform)+'views');
app.set('view options',{layout:false});


app.use(bodyParder.urlencoded({extended:true}));
app.use(bodyParder.json());
app.use(cookie());
app.use(session({
  secret: 'keyboard cat',
  resave: false,
  saveUninitialized: true
}));
app.use(logger()).use(function(req,res,next){
  if(res.statusCode!=200)
  {
     setTimeout(function(){
        res.end('server is Delay!');
        return false;
     },time);
  }else{
     next();
  }
});

app.use('/',routers);
app.use('/static',express.static(dirname+'/public'));
app.use(function(req,res,next){
   var err = new Error('no Found');
   err.status = 404;
   if(err)
   {
      res.end('no Found view!');
      return false;
   }else{
   	  next();
   } 
});


//开发模式和生产模式
if(env==="development")
{
   app.use(function(req,res,next){

   }); 
}else{
   app.use(function(req,res,next){

   });
}


app.listen(port,function(){
	console.log('start is success');
});

//检验系统模式，对目录格式处理
function checkPlat(platform)
{
    var plt = platform.toString().toLowerCase(),
        direxc = '/';
    eval("/"+systems.win+"/").test(plt) ? (direxc="\\") : direxc;
    return direxc;
}