//data.js
/*
    数据：
      
      tabTitle   tab切换标题数据
      tabContent  tab切换对应数据
      tabBottomBar  底部tab数据
      myKnowldegemap 结构图谱
      searchModule  搜索模块数据 
      searchContent  搜索成功返回数据
         knowledgemap->知识图谱
         knowledgefeatured->知识精选
      //articleDetails详情页面数据待定......  

    标注添加
       AddFlg 
          tabTitle 
              tab当前样式，变换样式设置
          tabBottomBar
              底部tab当前样式，变换样式设置  
          searchModule
              搜索模块状态切换，下拉提供提示字段，聚焦状态设置，默认值设置            

    标注介绍
      title,text标题，文本数据
      titles 数据层级关系标题
      src/pic 图片地址
      href 跳转地址
      root 是否标注上当前样式
      id 内容ID号
      classi 分类
      loadingheight->loading层高度设定


      //prompt:'推荐：Java',
*/

exports.datas = {
   AddFlg:{
       tabTitle:[{
            tag:"root",
            value:"recommend-root"
        }],
       tabBottomBar:[{
           tag:"root",
           value:"root"
       }],
       searchModule:[{
           tag:"searchstatus",
           value:""
       },{
           tag:"infortext",
           value:"搜索："
       },{
           tag:"focus",
           value:false
       }] 
   },  
   tabTitle:[{
         id:'',
         title:'知识图谱'
      },{
         title:'知识精选'
    }],
   tabContent:{
          "contentlist":[
             {
               "knowledgemap":[{
                  pic:'../../images/test.jpg',
                  title:'Java知识图谱0',
                  pernum:'99',
                  knnum:'9999',
                  href:'../map/map',
                  id:'1',
                  classi:'Java'
                },{
                  pic:'../../images/test.jpg',
                  title:'Scala知识图谱知识图识图谱知识图谱知识图谱知识图谱Scala知识图谱Scala知识图谱Scala知识图谱Scala知识图谱Scala知识图谱1',
                  pernum:'99',
                  knnum:'9999',
                  href:'../map/map',
                  id:'2',
                  classi:'Scala2'
                },{
                  pic:'../../images/test.jpg',
                  title:'Scala知识图谱2',
                  pernum:'99',
                  knnum:'9999',
                  href:'../map/map',
                  id:'2',
                  classi:'Scala2'
                },{
                  pic:'../../images/test.jpg',
                  title:'Scala知识图谱3',
                  pernum:'99',
                  knnum:'9999',
                  href:'../map/map',
                  id:'2',
                  classi:'Scala2'
                },{
                  pic:'../../images/test.jpg',
                  title:'Scala知识图谱4',
                  pernum:'99',
                  knnum:'9999',
                  href:'../map/map',
                  id:'2',
                  classi:'Scala2'
                },{
                  pic:'../../images/test.jpg',
                  title:'Scala知识图谱5',
                  pernum:'99',
                  knnum:'9999',
                  href:'../map/map',
                  id:'2',
                  classi:'Scala2'
                },{
                  pic:'../../images/test.jpg',
                  title:'Scala知识图谱6',
                  pernum:'99',
                  knnum:'9999',
                  href:'../map/map',
                  id:'2',
                  classi:'Scala2'
                },{
                  pic:'../../images/test.jpg',
                  title:'Scala知识图谱7',
                  pernum:'99',
                  knnum:'9999',
                  href:'../map/map',
                  id:'2',
                  classi:'Scala2'
                }],
                size:8,
                oh:'200'
             },{
               "knowledgefeatured":[{
                  title:'Gazebo機器人仿真學習探索筆記azebo機器人仿真學習探索筆記（三）機...',
                  subtitle:'Swift',
                  pernum:'999',
                  href:'../details/details',
                  id:'3',
                  classi:'Gazebo1',
                  content:{
                      src:'',
                      collectors:'',
                      article:'【大白，卖的一手好萌】一波三折，妙趣横生。悬疑和温情，搞笑与动作，即使拍成真人版也绝对是一部好题材和好故事。大白呆萌可爱一逗比，细节刻画真实有趣，放气如放屁，'
                  }
               },{
                  title:'Serializable和Parcelable的Parcelable的Pable的再次回忆',
                  subtitle:'Swift',
                  pernum:'999',
                  href:'../details/details',
                  id:'4',
                  classi:'Gazebo2',
                  content:''  
               },{
                  title:'UI组件：TextView及其子类',
                  subtitle:'Swift',
                  pernum:'999',
                  href:'../details/details',
                  id:'5',
                  classi:'Gazebo3',
                  content:''  
               },{
                  title:'UI组件：TextView及其子类',
                  subtitle:'Swift',
                  pernum:'999',
                  href:'../details/details',
                  id:'5',
                  classi:'Gazebo3',
                  content:''  
               },{
                  title:'UI组件：TextView及其子类',
                  subtitle:'Swift',
                  pernum:'999',
                  href:'../details/details',
                  id:'5',
                  classi:'Gazebo3',
                  content:''  
               },{
                  title:'UI组件：TextView及其子类',
                  subtitle:'Swift',
                  pernum:'999',
                  href:'../details/details',
                  id:'5',
                  classi:'Gazebo3',
                  content:''  
               },{
                  title:'UI组件：TextView及其子类',
                  subtitle:'Swift',
                  pernum:'999',
                  href:'../details/details',
                  id:'5',
                  classi:'Gazebo3',
                  content:''  
               },{
                  title:'UI组件：TextView及其子类',
                  subtitle:'Swift',
                  pernum:'999',
                  href:'../details/details',
                  id:'5',
                  classi:'Gazebo3',
                  content:''  
               },{
                  title:'UI组件：TextView及其子类',
                  subtitle:'Swift',
                  pernum:'999',
                  href:'../details/details',
                  id:'5',
                  classi:'Gazebo3',
                  content:''  
               },{
                  title:'UI组件：TextView及其子类',
                  subtitle:'Swift',
                  pernum:'999',
                  href:'../details/details',
                  id:'5',
                  classi:'Gazebo3',
                  content:''  
               },{
                  title:'UI组件：TextView及其子类',
                  subtitle:'Swift',
                  pernum:'999',
                  href:'../details/details',
                  id:'5',
                  classi:'Gazebo3',
                  content:''  
               },{
                  title:'UI组件：TextView及其子类s',
                  subtitle:'Swift',
                  pernum:'999',
                  href:'../details/details',
                  id:'5',
                  classi:'Gazebo3',
                  content:''  
               },{
                  title:'UI组件：TextView及其子类s',
                  subtitle:'Swift',
                  pernum:'999',
                  href:'../details/details',
                  id:'5',
                  classi:'Gazebo3',
                  content:''  
               },{
                  title:'UI组件：TextView及其子类s',
                  subtitle:'Swift',
                  pernum:'999',
                  href:'../details/details',
                  id:'5',
                  classi:'Gazebo3',
                  content:''  
               },{
                  title:'UI组件：TextView及其子类s',
                  subtitle:'Swift',
                  pernum:'999',
                  href:'../details/details',
                  id:'5',
                  classi:'Gazebo3',
                  content:''  
               },{
                  title:'UI组件：TextView及其子类s',
                  subtitle:'Swift',
                  pernum:'999',
                  href:'../details/details',
                  id:'5',
                  classi:'Gazebo3',
                  content:''  
               },{
                  title:'UI组件：TextView及其子类s1',
                  subtitle:'Swift',
                  pernum:'999',
                  href:'../details/details',
                  id:'5',
                  classi:'Gazebo3',
                  content:''  
               }],
                size:17,
                oh:'200'
             }
          ]
    },
    myKnowldegemap:{
        structmap:[
            {
              title:'Java',
              titles:'Java',
              id:'',
              href:'../list/list',
              child:[{ 
                      id:1,
                      titles:'Java一Java基础－1',
                      title:'Java基础－1',
                      href:'../list/list',
                      child:[{
                          id:'0-1',
                          titles:'Java一Java基础－1一Java基础－1-1',
                          title:'Java基础－1-1',
                          href:'../list/list',
                          child:[{
                             id:'0-1-1',
                             titles:'Java一Java基础－1一Java基础－1-1一Java基础－1-1-1',
                             title:'Java基础－1-1-1',
                             href:'../list/list',
                             child:[{
                                id:'0-1-1-1',
                                titles:'Java一Java基础－1一Java基础－1-1一Java基础－1-1-1一Java基础－1-1-1-1',
                                title:'Java基础－1-1-1-1',
                                href:'../list/list'
                             }]
                          }]
                      }]
               },{
                      id:2,
                      titles:'Java一Java基础－2',
                      title:'Java基础－2',
                      href:'../list/list',
                      child:[{
                          id:'2-1',
                          titles:'Java一Java基础－2一Java基础－2-1',
                          title:'Java基础－2-1',
                          href:'../list/list'
                      },{
                          id:'2-2',
                          titles:'Java一Java基础－2一Java基础－2-2',
                          title:'Java基础－2-2',
                          href:'../list/list'
                      }]
               },{
                    id:3,
                    titles:'Java一Java基础－3',
                    title:'Java基础－3',
                    href:'../list/list'
               }]
            }
        ]
    },
    searchContent:[
      {
          knowledgemap:[{
            pic:'../../images/test.jpg',
            title:'Java知识图谱0',
            pernum:'99',
            knnum:'9999',
            href:'../map/map',
            id:'1',
            classi:'Java1'
        },{
            pic:'../../images/test.jpg',
            title:'Java知识图谱0',
            pernum:'99',
            knnum:'9999',
            href:'../map/map',
            id:'1',
            classi:'Java2'
        }]
      },{
          knowledgefeatured:[{
            title:'Gazebo機器人仿真學習探索筆記1...',
            subtitle:'Swift1',
            pernum:'999',
            href:'../details/details',
            id:'3',
            classi:'Gazebo1',
            content:{
                src:'',
                collectors:'',
                article:'【大白，卖的一手好萌】一波三折，妙趣横生。悬疑和温情，搞笑与动作，即使拍成真人版也绝对是一部好题材和好故事。大白呆萌可爱一逗比，细节刻画真实有趣，放气如放屁，'
            }
        },{
            title:'Gazebo機器人仿真學習探索筆記2...',
            subtitle:'Swift2',
            pernum:'999',
            href:'../details/details',
            id:'3',
            classi:'Gazebo1',
            content:{
                src:'',
                collectors:'',
                article:'【大白，卖的一手好萌】一波三折，妙趣横生。悬疑和温情，搞笑与动作，即使拍成真人版也绝对是一部好题材和好故事。大白呆萌可爱一逗比，细节刻画真实有趣，放气如放屁，'
            }
        }]  
      }
    ],
    tabBottomBar:[{
        id:'',
        text:'我的图谱',
        href:'../map/map'
     },{
        id:'',
        text:'推荐',
        href:'../recommend/recommend'
     },{
        id:'',
        text:'搜索',
        href:'../search/search'
    }],
    searchModule:{
       lecontent:[{
          id:'',
          text:'推荐'
       },{
          id:'',
          text:'我的'
       }]
    }
};
